### ISSUE TITLE
Use Azure Compute Gallery images from subscription?

### ISSUE THREAD

**Issue by rockwell-bkrische** [cloudbase/garm-provider-azure#9]
I don't see it documented anywhere, but is it possible to use your own custom images from an Azure Computer Gallery in the subscription? If so, how would I do that?

**Comment by gabriel-samfira** [comment]
Theoretically, if you have an URN associated, and it's accessible to you, you can use it. The image URN is translated to an Azure ARM image reference consisting of an [Offer, Publisher, SKU and version](https://github.com/cloudbase/garm-provider-azure/blob/main/internal/spec/spec.go#L337-L342).

I am sorry about the really late reply!

**Comment by gabriel-samfira** [comment]
feel free to re-open this issue if you need to.

**Comment by gabriel-samfira** [comment]
Okay, I completely missed the point of what you were saying, but hopefully #16 actually fixes this and you can simply reference the image by ID instead of URN.
